[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:production"

[deploy]
startCommand = "npm run start:production"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
